### ISSUE TITLE
scala-library is getting bundled with libraryDependencies, even if bundleScalaLibrary is set to false

### ISSUE THREAD

**Issue by moglideveloper** [JetBrains/sbt-idea-plugin#106]
If any libraryDepencies is used, then scala-library is also get bundled even when bundleScalaLibrary is set to false.

Below is the command that is used to package plugin :-
`sbt clean compile packageArtifact`

Simplified project to reproduce this issue :-
https://github.com/moglideveloper/SamplePlugin

**build.sbt**
```

name := "sample"

scalaVersion := "2.13.2"
ThisBuild / intellijPluginName := "LogicOverCode"
ThisBuild / intellijBuild := "211.7142.13"
ThisBuild / intellijPlatform := intellijPlatform.in(Global).??(IntelliJPlatform.IdeaCommunity).value
ThisBuild / bundleScalaLibrary  := false

intellijPlugins += "org.intellij.scala:2021.1.18".toPlugin

// scala library is coming with this dependency
libraryDependencies += "com.github.pathikrit" %% "better-files" % "3.9.1"

lazy val scalaIntellij = project.in(file("."))
  .enablePlugins(SbtIdeaPlugin)

```

**Comment by mutcianm** [comment]
This is actually related to https://github.com/sbt/sbt/issues/4632
scala-library is correctly added to "Provided" but still ends up in the "Compile" scope because it's a transitive dependency of "better-files" which is an expected sbt behaviour.
I guess the only reasonable solution is to explicitly filter out all scala-library instances from the resulting classpath.
